global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 10.255.255.253:9100
- job_name: pihole
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
     - 10.255.255.253:9617
- job_name: mikrotik
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - mktxp:49090
- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      - http://prometheus.io
      - https://heise.de
      - https://google.com
      - https://youtube.com
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
- job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
  static_configs:
    - targets: ['blackbox:9115']
# - job_name: 'blackbox_dns'
#   metrics_path: /probe
#   params:
#     module: [dns]
#   static_configs:
#     - targets:
#       - example.com:10.255.255.253
#       - example.com:8.8.8.8
#       - example.com:1.1.1.1
#       - youtube.com:10.255.255.253
#       - youtube.com:8.8.8.8
#       - youtube.com:1.1.1.1
#   relabel_configs:
#     - source_labels: [__address__]
#       target_label: __param_target
#     - source_labels: [__param_target]
#       target_label: instance
#     - source_labels: [__param_target]
#       regex: '(.*):.*$'
#       replacement: '$1'
#       target_label: 'domain'
#     - source_labels: [__param_target]
#       regex: '.*:(.*)$'
#       replacement: '$1'
#       target_label: 'instance'
#     - source_labels: [__param_target]
#       regex: '(.*):.*$'
#       replacement: '$1'
#       target_label: __param_module
#     - source_labels: [__param_target]
#       regex: '.*:(.*)$'
#       replacement: '$1'
#       target_label: __param_target
#     - target_label: __address__
#       replacement: blackbox:9115
