---
# tasks file for 1password-cli


- name: install unzip
  apt:
    name: unzip
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Downlaod and extract 1password cli
  ansible.builtin.unarchive:
    src: https://cache.agilebits.com/dist/1P/op2/pkg/v2.16.1/op_linux_amd64_v2.16.1.zip
    dest: /usr/local/bin
    remote_src: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
