global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['{{ ansible_fqdn }}:9100']

remote_write:
  - url: "{{ grafana_prometheus_remote_write_endpoint }}"
    basic_auth:
      username: "{{ grafana_prometheus_username }}"
      password: "{{ grafana_prometheus_password }}"
