---
# tasks file for jenkins-ssh-access

- name: sanity check jenkins public key
  fail: msg="The jenkins ssh key is missing"
  when: jenkins_public_ssh_key | length == 0

- name: Add jenkins group
  ansible.builtin.group:
    name: jenkinsci

- name: Add jenkins user
  ansible.builtin.user:
    name: jenkinsci
    group: jenkinsci
    home: /var/lib/jenkins
    shell: /bin/bash
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# add jenkins user to the admin group if running on mac to allow ssh access
- name: Add jenkins user
  ansible.builtin.user:
    name: jenkinsci
    group: jenkinsci
    groups: admin
    home: /var/lib/jenkins
    shell: /bin/zsh
  when: ansible_distribution == 'MacOSX'

- name: Add jenkins public key
  ansible.posix.authorized_key:
    user: "jenkinsci"
    state: present
    key: "{{ jenkins_public_ssh_key }}"

- name: Create home dir
  ansible.builtin.file:
    path: /var/lib/jenkins
    state: directory
    mode: '0755'
    owner: jenkinsci
    group: jenkinsci

- name: Allow 'jenkinsci' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^jenkinsci'
    line: 'jenkinsci ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Install java
  apt:
    name: default-jdk
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install java
  community.general.homebrew:
    name:
      - openjdk@11
  become: true
  become_user: jenkinsci
  when: ansible_distribution == 'MacOSX'

- name: Ensure virtualenv is installed
  ansible.builtin.command: python3 -m venv /var/lib/jenkins/venv
  args:
    creates: /var/lib/jenkins/venv

- name: Install ansible for the jenkinsci user
  ansible.builtin.pip:
    name: ansible
    virtualenv: /var/lib/jenkins/venv
  # ansible install on plex server broken atm
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure venv access
  ansible.builtin.file:
    path: /var/lib/jenkins/venv
    state: directory
    mode: '0755'
    owner: jenkinsci
    group: jenkinsci
