---
version: '3.8'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  pihole_exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole_exporter
    network_mode: host
    environment:
      PIHOLE_HOSTNAME: "10.255.255.253"
      PIHOLE_API_TOKEN: entertokenhere
      PORT: "9617"
    ports:
      - "9617:9617"


