---
#
# this workflow "updates" software versions for node-a and node-b
#

name: "update-versions"

on:
  # allow for manual execution
  workflow_dispatch:
  # run once a week
  schedule:
    - cron: '0 3 * * 1'

permissions: write-all

env:
  WORDPRESS_SFTP_PASSWORD: ${{ secrets.WORDPRESS_COM_SFTP_PASSWORD }}

jobs:
  update-versions:
    name: "Update local versions"
    runs-on: "ubuntu-latest"
    permissions: write-all

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          path: infrastructure

      - name: "Checkout update-versions repository"
        uses: actions/checkout@v3
        with:
          path: update-versions
          repository: huttercloud/update-versions
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update-versions/requirements.txt
      - name: Update versions
        run: |
          python3 update-versions/update-versions.py \
            --file infrastructure/terraform/resources/home/node-a/locals.tf \
            --file infrastructure/terraform/resources/home/node-b/locals.tf \
            --replace '\s*?external_dns_version\s*?=\s+\"(.*?)\"' EXTERNALDNS \
            --replace '\s*?external_secrets_version\s*?=\s+\"(.*?)\"' EXTERNALSECRETS \
            --replace '\s*?pi_hole_version\s*?=\s+\"(.*?)\"' PIHOLE \
            --replace '\s*?wireguard_version\s*?=\s+\"(.*?)\"' WIREGUARD \
            --replace '\s*?unifi_version\s*?=\s+\"(.*?)\"' UNIFICONTROLLER \
            --replace '\s*?argo_cd_version\s*?=\s+\"(.*?)\"' ARGOCD
      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v4
        with:
          path: infrastructure
          commit-message: "chore(update): Update versions"
          branch: "chore/update-versions-${{ steps.date.outputs.date }}"
          delete-branch: true
          title: "chore: Update versions ${{ steps.date.outputs.date }}"
          reviewers: |
            sebastianhutter
